-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 11:58:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ar_condicionado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ar_condicionado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ar_condicionado` DEFAULT CHARACTER SET utf8 ;
USE `ar_condicionado` ;

-- -----------------------------------------------------
-- Table `ar_condicionado`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar_condicionado`.`produtos` (
  `id_produtos` INT(11) NOT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `produto` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `valor` DECIMAL(9,2) NULL DEFAULT NULL,
  `img_produto` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
